version: '3.8'

services:
  # Redis service for email storage
  redis:
    image: redis:7-alpine
    container_name: turbomail-redis
    restart: unless-stopped
    ports:
      - "6379:6379"
    volumes:
      - ./redis.conf:/usr/local/etc/redis/redis.conf
      - redis_data:/data
    command: redis-server /usr/local/etc/redis/redis.conf
    networks:
      - turbomail-network
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 30s
      timeout: 10s
      retries: 3

  # TurboMails Express API server
  api:
    build:
      context: .
      dockerfile: Dockerfile.api
    container_name: turbomail-api
    restart: unless-stopped
    ports:
      - "5000:5000"
    environment:
      - NODE_ENV=production
      - PORT=5000
      - REDIS_URL=redis://redis:6379
    depends_on:
      redis:
        condition: service_healthy
    networks:
      - turbomail-network
    volumes:
      - ./logs:/app/logs

  # Next.js frontend
  frontend:
    build:
      context: .
      dockerfile: Dockerfile.frontend
    container_name: turbomail-frontend
    restart: unless-stopped
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=production
      - NEXT_PUBLIC_API_URL=http://localhost:5000
    depends_on:
      - api
    networks:
      - turbomail-network

  # Haraka SMTP server
  smtp:
    build:
      context: .
      dockerfile: Dockerfile.smtp
    container_name: turbomail-smtp
    restart: unless-stopped
    ports:
      - "25:25"
      - "587:587"
    environment:
      - NODE_ENV=production
      - API_URL=http://api:5000
    depends_on:
      - api
    networks:
      - turbomail-network
    volumes:
      - ./haraka-config:/app/haraka-config
      - ./logs:/app/logs

  # Nginx reverse proxy (optional)
  nginx:
    image: nginx:alpine
    container_name: turbomail-nginx
    restart: unless-stopped
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
      - ./ssl:/etc/nginx/ssl
    depends_on:
      - frontend
      - api
    networks:
      - turbomail-network

volumes:
  redis_data:
    driver: local

networks:
  turbomail-network:
    driver: bridge